
spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: spring-ai-tests
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/chatMemory?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
  autoconfigure:
    exclude:
      - org.springframework.ai.autoconfigure.chat.client.ChatClientAutoConfiguration
      - org.springframework.ai.autoconfigure.ollama.OllamaAutoConfiguration
  jackson:
    default-property-inclusion: non_null
    deserialization:
      fail-on-unknown-properties: false
  ai:
    openai:
      api-key: ${SILICONFLOW_API_KEY}  # apiKey到硅基流动官网获取免费的
      base-url: https://api.siliconflow.cn
      chat:
        options:
          model: deepseek-ai/DeepSeek-V3 # 使用通义千问模型
          temperature: 0.7
server:
  port: 8080
  servlet:
    context-path: /api
